name: Dependency Review
on:
  pull_request:
    paths: # Trigger only if package.json changes
      - '**/package.json'
  push:
    branches:
      - health-score-test

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    name: Analyze New Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20.18.2'
          cache: 'npm'

      - name: Install Dependencies for Script
        run: npm install axios semver @octokit/rest@18.12.0 @actions/core
        working-directory: ./.github/scripts

      - name: Run Dependency Analysis Script
        id: analysis
        run: node .github/scripts/check_dependency_health.js
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_TOKEN: ${{ secrets.KIBANAMACHINE_TOKEN }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
          EVENT_NAME: ${{ github.event_name }}
          AFTER_SHA: ${{ github.event.after }}
      - name: Notify Slack on Low Score
        if: steps.analysis.outputs.breaches_dependency_slo == 'true'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.CODE_SCANNING_SLACK_TOKEN }}
          payload: |
            "channel": ${{ secrets.CODE_SCANNING_SLACK_CHANNEL_ID }}
            "text": ":warning: *Low Dependency Score Alert!* :warning:"
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "One or more newly added dependencies scored below the threshold (0.65)."
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Pull Request"
                    },
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                ]
              }
            ]
